### ISSUE TITLE
Error when install package

### ISSUE THREAD

**Issue by PePoDev** [fatihkahveci/gin-inspector#1]
`go get github.com/fatihkahveci/gin-inspector`
console log
go: finding github.com/fatihkahveci/gin-inspector latest
go: downloading github.com/fatihkahveci/gin-inspector v0.0.0-20190208215146-ffbe3a21bb6b
go get github.com/fatihkahveci/gin-inspector: zip: not a valid zip file

**Comment by fatihkahveci** [comment]
@PePoDev 
`➜  ~ go get github.com/fatihkahveci/gin-inspector

go: finding github.com/fatihkahveci/gin-inspector latest
go: downloading github.com/fatihkahveci/gin-inspector v0.0.0-20190208215146-ffbe3a21bb6b
go: extracting github.com/fatihkahveci/gin-inspector v0.0.0-20190208215146-ffbe3a21bb6b
go: downloading golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
go: extracting golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
➜  ~`

Can you try again?

**Comment by PePoDev** [comment]
@fatihkahveci Still error

**Comment by fatihkahveci** [comment]
@PePoDev

Can you send `go env` response?

**Comment by PePoDev** [comment]
@fatihkahveci 
Sure

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\PePoDev\AppData\Local\go-build
set GOENV=C:\Users\PePoDev\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Go\work
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\PePoDev\AppData\Local\Temp\go-build957512490=/tmp/go-build -gno-record-gcc-switches

**Comment by fatihkahveci** [comment]
I just test Linux and macOS env. I need to investigate this issue to Windows en.

Also you can download any other go repo?

**Comment by PePoDev** [comment]
@fatihkahveci  Yes, I can.

This list from go.mod, I use `go get` success

> 	github.com/chenjiandongx/ginprom v0.0.0-20191009020913-18c8180e08e3
> 	github.com/danielkov/gin-helmet v0.0.0-20171108135313-1387e224435e
> 	github.com/dvwright/xss-mw v0.0.0-20190914040805-e2470e975ed5
> 	github.com/gin-contrib/cors v1.3.0
> 	github.com/gin-contrib/sessions v0.0.0-20190101140330-dc5246754963
> 	github.com/gin-contrib/sse v0.1.0 // indirect
> 	github.com/gin-gonic/gin v1.4.0
> 	github.com/kubastick/ginception v0.0.0-20190206211325-fd09442c2802
> 	github.com/mattn/go-isatty v0.0.10 // indirect
> 	github.com/microcosm-cc/bluemonday v1.0.2 // indirect
> 	github.com/prometheus/client_golang v1.1.0
> 	github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4 // indirect
> 	github.com/prometheus/common v0.7.0 // indirect
> 	github.com/prometheus/procfs v0.0.5 // indirect
> 	github.com/stretchr/testify v1.4.0 // indirect
> 	github.com/tpkeeper/gin-dump v0.1.0
> 	github.com/ugorji/go v1.1.7 // indirect
> 	github.com/utrack/gin-csrf v0.0.0-20190424104817-40fb8d2c8fca
> 	go.uber.org/atomic v1.4.0 // indirect
> 	go.uber.org/multierr v1.2.0 // indirect
> 	go.uber.org/zap v1.10.0
> 	gopkg.in/yaml.v2 v2.2.4 // indirect

**Comment by fatihkahveci** [comment]
@PePoDev hey, when i try to windows env still everything fine

`go get -u -v github.com/fatihkahveci/gin-inspector
github.com/fatihkahveci/gin-inspector (download)
github.com/gin-gonic/gin (download)
github.com/gin-contrib/sse (download)
github.com/golang/protobuf (download)
github.com/ugorji/go (download)
get "gopkg.in/go-playground/validator.v9": found meta tag get.metaImport{Prefix:"gopkg.in/go-playground/validator.v9", VCS:"git", RepoRoot:"https://gopkg.in/go-playground/validator.v9"} at //gopkg.in/go-playground/validator.v9?go-get=1
gopkg.in/go-playground/validator.v9 (download)
github.com/go-playground/universal-translator (download)
github.com/go-playground/locales (download)
github.com/leodido/go-urn (download)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/mattn/go-isatty (download)`

Can you try with -v flag. Maybe we can see more clear log

**Comment by PePoDev** [comment]
I don't know what happen. But It fine now. Thanks.
